src/MD/Bundle/CMSBundle/Entity/Client.php
<?php

namespace MD\Bundle\CMSBundle\Entity;

use MD\Bundle\MediaBundle\Entity\Image as Image;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Client
 * @ORM\Table("client")
 * @ORM\Entity
 */
class Client {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var text
     *
     * @ORM\Column(name="name", type="text", type="string", length=45, nullable = false)
     */
    private $name;

    /**
     * @var text
     *
     * @ORM\Column(name="note", type="text", nullable = true)
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity="\MD\Bundle\MediaBundle\Entity\Image")
     */
    protected $images;

    /**
     * @var integer
     *
     * @ORM\Column(name="placement", type="integer")
     */
    protected $placement;

    /**
     * @var integer
     *
     * @ORM\Column(name="home_page", type="boolean")
     */
    protected $homePage;

    public function __toString() {
        return $this->getNote();
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->images = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Photo
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set note
     *
     * @param string $note
     * @return Photo
     */
    public function setNote($note) {
        $this->note = $note;

        return $this;
    }

    /**
     * Get note
     *
     * @return string 
     */
    public function getNote() {
        return $this->note;
    }

    /**
     * Add images
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $images
     * @return Photo
     */
    public function addImage(\MD\Bundle\MediaBundle\Entity\Image $images) {
        $this->images[] = $images;

        return $this;
    }

    /**
     * Remove images
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $images
     */
    public function removeImage(\MD\Bundle\MediaBundle\Entity\Image $images) {
        $this->images->removeElement($images);
    }

    /**
     * Set image
     *
     * @param \MD\Bundle\MediaBundle\Entity\Image $image
     * @return DynamicPage
     */
    public function setImage(\MD\Bundle\MediaBundle\Entity\Image $image = null) {
        $this->images[0] = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \MD\Bundle\MediaBundle\Entity\Image
     */
    public function getMainImage() {
        return $this->images[0];
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getImages() {
        return $this->images;
    }

    /**
     * Set placement
     *
     * @param integer $placement
     * @return Client
     */
    public function setPlacement($placement) {
        $this->placement = $placement;

        return $this;
    }

    /**
     * Get placement
     *
     * @return integer 
     */
    public function getPlacement() {
        return $this->placement;
    }


    /**
     * Set homePage
     *
     * @param boolean $homePage
     * @return Client
     */
    public function setHomePage($homePage)
    {
        $this->homePage = $homePage;
    
        return $this;
    }

    /**
     * Get homePage
     *
     * @return boolean 
     */
    public function getHomePage()
    {
        return $this->homePage;
    }
}

src/MD/Bundle/CMSBundle/Form/ClientType.php
<?php

namespace MD\Bundle\CMSBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ClientType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('name')
                ->add('homePage', null, array('label' => 'Show on Home Page', 'required' => FALSE))
                ->add('placement', 'choice', array(
                    'choices' => array(
                        3 => 'Global engineering & supply',
                        4 => 'Med. trade',
                        5 => 'Technology',
                        6 => '4Sale egypt',
//                        7 => 'Global for real estate development',
                    ),
                ))
                ->add('note')
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'MD\Bundle\CMSBundle\Entity\Client'
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'md_bundle_cmsbundle_client';
    }

}

src/MD/Bundle/CMSBundle/Controller/Administration/BannerController.php
<?php

namespace MD\Bundle\CMSBundle\Controller\Administration;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use MD\Bundle\CMSBundle\Entity\Banner;
use MD\Bundle\CMSBundle\Entity\Translation\BannerTranslation;
use MD\Bundle\CMSBundle\Form\BannerType;
use MD\Bundle\MediaBundle\Controller\ImageController;

/**
 * Banner controller.
 *
 * @Route("/banner")
 */
class BannerController extends Controller {

    /**
     * Lists all Banner entities.
     *
     * @Route("/", name="banner")
     * @Method("GET")
     * @Template()
     */
    public function indexAction() {
        $em = $this->getDoctrine()->getManager();
//        $entities = $em->getRepository('CMSBundle:Banner')->findAll();
        $entities = $em->getRepository('CMSBundle:Banner')->findAll();
        return array(
            'entities' => $entities,
        );
    }

    /**
     * Creates a new Banner entity.
     *
     * @Route("/", name="banner_create")
     * @Method("POST")
     * @Template("CMSBundle:Banner:new.html.twig")
     */
    public function createAction(Request $request) {
        $entity = new Banner();
        $form = $this->createForm(new BannerType(), $entity);

        $uploadForm = $this->createForm(new \MD\Bundle\MediaBundle\Form\SingleImageType());
        $formView = $uploadForm->createView();
        $uploadForm->bind($request);
        $data_upload = $uploadForm->getData();
        $file = $data_upload["file"];
        $form->bind($request);
        if ($this->getRequest()->request->get('open_type') != NULL) {
            $openType = $this->getRequest()->request->get('open_type');
        } else {
            $openType = 0;
        }
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
//            $entity->setPlacement(1); // HomePage
            $entity->setOpenType($openType);


            $em->persist($entity);
            $em->flush();

            // Upload Image
            $imageController = new ImageController();
            $imageController->uploadSingleImage($em, $entity, $file, 2);

            return $this->redirect($this->generateUrl('banner'));
        }

        return array(
            'entity' => $entity,
            'form' => $form->createView(),
            'upload_form' => $formView,
        );
    }

    /**
     * Displays a form to create a new Banner entity.
     *
     * @Route("/new", name="banner_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction() {
        $entity = new Banner();
        $form = $this->createForm(new BannerType(), $entity);
        $uploadForm = $this->createForm(new \MD\Bundle\MediaBundle\Form\SingleImageType());
        $formView = $uploadForm->createView();
        return array(
            'entity' => $entity,
            'form' => $form->createView(),
            'upload_form' => $formView,
        );
    }

    /**
     * Displays a form to edit an existing Banner entity.
     *
     * @Route("/{id}/edit", name="banner_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('CMSBundle:Banner')->find($id);
        $image = $entity->getImage();
        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Banner entity.');
        }
        $bannerType = new BannerType();
        $bannerType->placmentData = $entity->getPlacement();

        $uploadForm = $this->createForm(new \MD\Bundle\MediaBundle\Form\SingleImageType());
        $formView = $uploadForm->createView();
        $editForm = $this->createForm($bannerType, $entity);
        $deleteForm = $this->createDeleteForm($id);


        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'upload_form' => $formView,
            'image' => $image,
        );
    }

    /**
     * Edits an existing Banner entity.
     *
     * @Route("/{id}", name="banner_update")
     * @Method("PUT")
     * @Template("CMSBundle:Banner:edit.html.twig")
     */
    public function updateAction(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('CMSBundle:Banner')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Banner entity.');
        }
        $uploadForm = $this->createForm(new \MD\Bundle\MediaBundle\Form\SingleImageType());
        $formView = $uploadForm->createView();
        $uploadForm->bind($request);
        $data_upload = $uploadForm->getData();
        $file = $data_upload["file"];
        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createForm(new BannerType(), $entity);
        $editForm->bind($request);
        if ($this->getRequest()->request->get('open_type') != NULL) {
            $openType = $this->getRequest()->request->get('open_type');
        } else
            $openType = 0;
        if ($editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity->setOpenType($openType);

            // Upload Image
            $imageController = new ImageController();
            $imageController->uploadSingleImage($em, $entity, $file, 2);

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('banner_edit', array('id' => $id)));
        }

        return array(
            'entity' => $entity,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'upload_form' => $formView,
        );
    }

    /**
     * Deletes a Banner entity.
     *
     * @Route("/delete", name="banner_delete")
     * @Method("POST")
     */
    public function deleteAction() {
        $id = $this->getRequest()->request->get('id');
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('CMSBundle:Banner')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Banner entity.');
        }

        $em->remove($entity);
        $em->flush();

        return $this->redirect($this->generateUrl('banner'));
    }

    /**
     * Creates a form to delete a Banner entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id) {
        return $this->createFormBuilder(array('id' => $id))
                        ->add('id', 'hidden')
                        ->getForm()
        ;
    }

}

src/MD/Bundle/CMSBundle/Controller/Administration/DashboardController.php
<?php

namespace MD\Bundle\CMSBundle\Controller\Administration;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Response;

/**
 * Faq controller.
 *
 * @Route("/")
 */
class DashboardController extends Controller {

    /**
     * Lists all Faq entities.
     *
     * @Route("/", name="cms_dashboard")
     * @Method("GET")
     * @Template()
     */
    public function DashboardAction() {
        return $this->redirect($this->generateUrl('dynamicpage'));
    }

}

src/MD/Bundle/CMSBundle/Controller/Administration/SeoController.php
<?php

namespace MD\Bundle\CMSBundle\Controller\Administration;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use MD\Bundle\CMSBundle\Entity\Service;
use MD\Bundle\CMSBundle\Form\ServiceType;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\FormError;
use MD\Utils\Validate;
use Symfony\Component\HttpFoundation\Session\Session;

class SeoController extends Controller {

    protected $em = null;

    public function __construct(EntityManager $em) {
        $this->em = $em;
    }

    public function validateSeo(\MD\Bundle\CMSBundle\Entity\Seo $seo, $seoForm) {
        $session = new Session();
        $return = TRUE;
        if ($seo->getId() == NULL) {
            $checkSlug = $this->em->getRepository('CMSBundle:Seo')->findBy(array('slug' => $seo->getRawSlug()));
            if (count($checkSlug) > 0) {
                $session->getFlashBag()->add('error', 'the HTML Slug is duplicated, please change it');
                $return = FALSE;
            }
        } else {
            $checkSlug = $this->em->getRepository('CMSBundle:Seo')->queryBySlugAndNotId($seo->getRawSlug(), $seo->getId());
            if (count($checkSlug) > 0 and is_array($checkSlug)) {
                $session->getFlashBag()->add('error', 'the HTML Slug is duplicated, please change it');
                $return = FALSE;
            }
        }
        return $return;
    }

}

src/MD/Bundle/CMSBundle/Resources/views/Administration/Client/edit.html.twig
{% extends 'AdminTemplateBundle::base.html.twig' %}
{% set page_title %}Edit {{ entity.name }}{% endset %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/admintemplate/assets/plugins/validator/bootstrapValidator.min.css') }}" rel="stylesheet">
{% endblock %}

{% block body -%}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h6 class="panel-title"><i class="icon-bubble4"></i> {{ page_title }}</h6>
        </div>
        <div class="panel-body">
            <form class="form bootstrap-validator-form" id="validation" action="{{ path('client_update', { 'id': entity.id}) }}" role="form" method="POST" {{form_enctype(upload_form)}} {{ form_enctype(edit_form) }}>
                <input type="hidden" name="_method" value="PUT" />       
                <div class="row">
                    <div class="col-xs-6 col-md-9">
                        <div class="form-group">
                            <label>Photo</label>
                            <div class="input-group">
                                <input type="text" readonly="" class="form-control">
                                <span class="input-group-btn">
                                    <span class="btn btn-default btn-file">
                                        Browse… {{ form_widget(upload_form.file) }}
                                    </span>
                                </span>
                            </div><!-- /.input-group -->
                        </div>
                    </div>
                    {% if entity.mainImage %}
                        <div class="col-xs-6 col-md-3 magnific-popup-wrap">
                            <div class="col-lg-10">
                                <a title="" data-placement="top" data-toggle="tooltip" href="javascript:del('{{entity.mainImage.id}}')" class="btn btn-danger btn-xs btn-block tooltips" data-original-title="Delete">Delete</a>
                            </div>
                            <div class="item">
                                <a class="thumbnail square no-border zooming"  href="{{ asset("uploads/client/" ~ entity.id ~ "/"  ~ entity.mainImage.id) }}">
                                    <img src="{{ asset("uploads/client/" ~ entity.id ~ "/"  ~ entity.mainImage.id) }}" />
                                </a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                {{ form_widget(edit_form) }}
                <div class="form-group text-right">
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Update</button>
                    <button class="btn btn-danger" type="reset"><i class="fa fa-refresh"></i> Reset</button>
                </div>
            </form>
            {% if entity.mainImage %}
                <form hidden name="delete_form" id="delete_form" action="{{ path('clientimages_delete', { 'h_id': entity.id  , 'redirect_id' : 1 }) }}" method="POST"  >
                    <input type="hidden" name="id" id="imageId" />
                </form>
            {% endif %}
            <div >
                <a href="{{ path('client') }}" class="btn btn-warning">Back to the list</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/admintemplate/assets/plugins/validator/bootstrapValidator.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/admintemplate/assets/plugins/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
    <script type="text/javascript">
        $(function() {
            $('#validation').bootstrapValidator();
            if ($('.magnific-popup-wrap').length > 0) {
                $('.magnific-popup-wrap').each(function() {
                    "use strict";
                    $(this).magnificPopup({
                        delegate: 'a.zooming',
                        type: 'image',
                        removalDelay: 300,
                        mainClass: 'mfp-fade',
                        gallery: {
                            enabled: true
                        }
                    });
                });
            }

            /** BEGIN INPUT FILE **/
            if ($('.btn-file').length > 0) {
                $(document).on('change', '.btn-file :file', function() {
                    "use strict";
                    var input = $(this),
                            numFiles = input.get(0).files ? input.get(0).files.length : 1,
                            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                    input.trigger('fileselect', [numFiles, label]);
                });
                $('.btn-file :file').on('fileselect', function(event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                            log = numFiles > 1 ? numFiles + ' files selected' : label;
                    if (input.length) {
                        input.val(log);
                    } else {
                        if (log)
                            alert(log);
                    }
                });
            }
            /** END INPUT FILE **/

        });
        function del(id) {
            if (confirm("Are you sure you want to delete?")) {
                $('#imageId').val(id);
                $('#delete_form').submit();
            }
        }

    </script>   
{% endblock %}

src/MD/Bundle/CMSBundle/Resources/views/Administration/Client/index.html.twig
{% extends 'AdminTemplateBundle::base.html.twig' %}
{% set page_title %}Client List{% endset %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/admintemplate/assets/plugins/datatable/css/bootstrap.datatable.min.css') }}" rel="stylesheet">
{% endblock %}
{% block body -%}
    <div class="the-box text-right rounded">
        <a class="btn btn-success" href="{{ path('client_new') }}">Create a new entry</a>
    </div>
    <div class="the-box">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="datatable-example">
                <thead class="the-box dark full">
                    <tr>
                        <th>Id</th>
                        <th>Photo</th>
                        <th>Name</th>
                        <th>Placement</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entity in entities %}
                        <tr>
                            <td>{{ entity.id }}</td>
                            <td>
                                {% if entity.getMainImage %}
                                    <img src="{{ asset("uploads/client/" ~ entity.id ~ "/"  ~ entity.getMainImage.id) }}" width="75" />
                                {% endif %}
                            </td>
                            <td>{{ entity.name }}</td>
                            {% if entity.placement == 3 %}
                                {% set placement = 'Global engineering & supply' %}
                            {% elseif entity.placement == 4 %}
                                {% set placement = 'Med. trade' %}
                            {% elseif entity.placement == 5 %}
                                {% set placement = 'Technology' %}
                            {% elseif entity.placement == 6 %}
                                {% set placement = '4Sale egypt' %}
                            {% elseif entity.placement == 7 %}
                                {% set placement = 'Global for real estate development' %}
                            {% endif %}
                            <td>{{ placement }}</td>
                            <td>
                                <a href="{{ path('client_edit', { 'id': entity.id }) }}" class="btn btn-info" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i></a>
                                <a  href="#" onclick="javascript:del({{entity.id}})" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fa fa-minus"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <form hidden name="delete_form" id="delete_form" action="{{ path('client_delete') }}" method="POST"  >
        <input type="hidden" name="id" id="entityId" />
    </form>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/admintemplate/assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/admintemplate/assets/plugins/datatable/js/bootstrap.datatable.js') }}"></script>
    <script>
        function del(id) {
            if (confirm("Are you sure you want to delete?"))
            {
                $('#entityId').val(id);
                $('#delete_form').submit();
            }
        }
    </script>
{% endblock %}

src/MD/Bundle/CMSBundle/Resources/views/Administration/Client/new.html.twig
{% extends 'AdminTemplateBundle::base.html.twig' %}
{% set page_title %}Client creation{% endset %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/admintemplate/assets/plugins/validator/bootstrapValidator.min.css') }}" rel="stylesheet">
{% endblock %}

{% block body -%}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h6 class="panel-title"><i class="icon-bubble4"></i> {{ page_title }}</h6>
        </div>
        <div class="panel-body">
            <form class="form bootstrap-validator-form" id="validation" action="{{ path('client_create') }}" role="form" method="POST" {{form_enctype(upload_form)}} {{ form_enctype(form) }}>
                <div class="form-group">
                    <label>Photo</label>
                    <div class="input-group">
                        <input type="text" readonly="" class="form-control">
                        <span class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                Browse… {{ form_widget(upload_form.file) }}
                            </span>
                        </span>
                    </div><!-- /.input-group -->
                </div>
                {{ form_widget(form) }}
                <div class="form-group text-right">
                    <button class="btn btn-success" type="submit"><i class="fa fa-check"></i> Create</button>
                    <button class="btn btn-danger" type="reset"><i class="fa fa-refresh"></i> Reset</button>
                </div>
            </form>
            <div >
                <a href="{{ path('client') }}" class="btn btn-warning">Back to the list</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/admintemplate/assets/plugins/validator/bootstrapValidator.min.js') }}"></script>
    <script type="text/javascript">
        $(function() {
            $('#validation').bootstrapValidator();
            /** BEGIN INPUT FILE **/
            if ($('.btn-file').length > 0) {
                $(document)
                        .on('change', '.btn-file :file', function() {
                            "use strict";
                            var input = $(this),
                                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                            input.trigger('fileselect', [numFiles, label]);
                        });
                $('.btn-file :file').on('fileselect', function(event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                            log = numFiles > 1 ? numFiles + ' files selected' : label;

                    if (input.length) {
                        input.val(log);
                    } else {
                        if (log)
                            alert(log);
                    }
                });
            }
            /** END INPUT FILE **/

        });
    </script>   
{% endblock %}